"""Opcode definitions for the SK-02 8-bit computer."""

from dataclasses import dataclass
from enum import Enum, auto


class OperandType(Enum):
    """Types of operands for instructions."""

    NONE = auto()  # Implied addressing (1 byte)
    IMM8 = auto()  # 8-bit immediate value (2 bytes)
    IMM16 = auto()  # 16-bit immediate value (3 bytes)
    ADDR16 = auto()  # 16-bit address (3 bytes)


@dataclass(frozen=True)
class Opcode:
    """Opcode definition."""

    value: int
    operand: OperandType
    size: int


# Complete opcode table for SK-02 (214 opcodes)
OPCODES: dict[str, Opcode] = {
    # Simple opcodes (0-127)
    "NOP": Opcode(0, OperandType.NONE, 1),
    "0>A": Opcode(1, OperandType.NONE, 1),
    "0>B": Opcode(2, OperandType.NONE, 1),
    "1>A": Opcode(3, OperandType.NONE, 1),
    "1>B": Opcode(4, OperandType.NONE, 1),
    "FF>A": Opcode(5, OperandType.NONE, 1),
    "FF>B": Opcode(6, OperandType.NONE, 1),
    "LOAD_A": Opcode(7, OperandType.ADDR16, 3),
    "LOAD_B": Opcode(8, OperandType.ADDR16, 3),
    "STORE_A": Opcode(9, OperandType.ADDR16, 3),
    "STORE_B": Opcode(10, OperandType.ADDR16, 3),
    "A++": Opcode(11, OperandType.NONE, 1),
    "A--": Opcode(12, OperandType.NONE, 1),
    "A>>": Opcode(13, OperandType.NONE, 1),
    "A<<": Opcode(14, OperandType.NONE, 1),
    "B>>": Opcode(15, OperandType.NONE, 1),
    "B<<": Opcode(16, OperandType.NONE, 1),
    "SET_A": Opcode(17, OperandType.IMM8, 2),
    "SET_B": Opcode(18, OperandType.IMM8, 2),
    "ADD": Opcode(19, OperandType.NONE, 1),
    "SUB": Opcode(20, OperandType.NONE, 1),
    "NOT": Opcode(21, OperandType.NONE, 1),
    "AND": Opcode(22, OperandType.NONE, 1),
    "CMP": Opcode(23, OperandType.NONE, 1),
    "PUSH_A": Opcode(24, OperandType.NONE, 1),
    "PUSH_B": Opcode(25, OperandType.NONE, 1),
    "POP_A": Opcode(26, OperandType.NONE, 1),
    "POP_B": Opcode(27, OperandType.NONE, 1),
    "LOAD_A_CD": Opcode(28, OperandType.NONE, 1),
    "LOAD_B_CD": Opcode(29, OperandType.NONE, 1),
    "STORE_A_CD": Opcode(30, OperandType.NONE, 1),
    "STORE_B_CD": Opcode(31, OperandType.NONE, 1),
    "GOSUB": Opcode(32, OperandType.ADDR16, 3),
    "RETURN": Opcode(33, OperandType.NONE, 1),
    "JMP": Opcode(34, OperandType.ADDR16, 3),
    "JMP_A_POS": Opcode(35, OperandType.ADDR16, 3),
    "JMP_A_EVEN": Opcode(36, OperandType.ADDR16, 3),
    "JMP_B_POS": Opcode(37, OperandType.ADDR16, 3),
    "JMP_B_EVEN": Opcode(38, OperandType.ADDR16, 3),
    "JMP_ZERO": Opcode(39, OperandType.ADDR16, 3),
    "JMP_OVER": Opcode(40, OperandType.ADDR16, 3),
    "JMP_INTER": Opcode(41, OperandType.ADDR16, 3),
    "A>B": Opcode(42, OperandType.NONE, 1),
    "A>C": Opcode(43, OperandType.NONE, 1),
    "A>D": Opcode(44, OperandType.NONE, 1),
    "A>E": Opcode(45, OperandType.NONE, 1),
    "A>F": Opcode(46, OperandType.NONE, 1),
    "A>G": Opcode(47, OperandType.NONE, 1),
    "A>H": Opcode(48, OperandType.NONE, 1),
    "A>OUT_0": Opcode(49, OperandType.NONE, 1),
    "A>OUT_1": Opcode(50, OperandType.NONE, 1),
    "B>A": Opcode(51, OperandType.NONE, 1),
    "B>C": Opcode(52, OperandType.NONE, 1),
    "B>D": Opcode(53, OperandType.NONE, 1),
    "B>E": Opcode(54, OperandType.NONE, 1),
    "B>F": Opcode(55, OperandType.NONE, 1),
    "B>G": Opcode(56, OperandType.NONE, 1),
    "B>H": Opcode(57, OperandType.NONE, 1),
    "B>OUT_0": Opcode(58, OperandType.NONE, 1),
    "B>OUT_1": Opcode(59, OperandType.NONE, 1),
    "C>A": Opcode(60, OperandType.NONE, 1),
    "C>B": Opcode(61, OperandType.NONE, 1),
    "C>D": Opcode(62, OperandType.NONE, 1),
    "C>E": Opcode(63, OperandType.NONE, 1),
    "C>F": Opcode(64, OperandType.NONE, 1),
    "C>G": Opcode(65, OperandType.NONE, 1),
    "C>H": Opcode(66, OperandType.NONE, 1),
    "D>A": Opcode(67, OperandType.NONE, 1),
    "D>B": Opcode(68, OperandType.NONE, 1),
    "D>C": Opcode(69, OperandType.NONE, 1),
    "D>E": Opcode(70, OperandType.NONE, 1),
    "D>F": Opcode(71, OperandType.NONE, 1),
    "D>G": Opcode(72, OperandType.NONE, 1),
    "D>H": Opcode(73, OperandType.NONE, 1),
    "E>A": Opcode(74, OperandType.NONE, 1),
    "E>B": Opcode(75, OperandType.NONE, 1),
    "E>C": Opcode(76, OperandType.NONE, 1),
    "E>D": Opcode(77, OperandType.NONE, 1),
    "E>F": Opcode(78, OperandType.NONE, 1),
    "E>G": Opcode(79, OperandType.NONE, 1),
    "E>H": Opcode(80, OperandType.NONE, 1),
    "F>A": Opcode(81, OperandType.NONE, 1),
    "F>B": Opcode(82, OperandType.NONE, 1),
    "F>C": Opcode(83, OperandType.NONE, 1),
    "F>D": Opcode(84, OperandType.NONE, 1),
    "F>E": Opcode(85, OperandType.NONE, 1),
    "F>G": Opcode(86, OperandType.NONE, 1),
    "F>H": Opcode(87, OperandType.NONE, 1),
    "G>A": Opcode(88, OperandType.NONE, 1),
    "G>B": Opcode(89, OperandType.NONE, 1),
    "G>C": Opcode(90, OperandType.NONE, 1),
    "G>D": Opcode(91, OperandType.NONE, 1),
    "G>E": Opcode(92, OperandType.NONE, 1),
    "G>F": Opcode(93, OperandType.NONE, 1),
    "G>H": Opcode(94, OperandType.NONE, 1),
    "H>A": Opcode(95, OperandType.NONE, 1),
    "H>B": Opcode(96, OperandType.NONE, 1),
    "H>C": Opcode(97, OperandType.NONE, 1),
    "H>D": Opcode(98, OperandType.NONE, 1),
    "H>E": Opcode(99, OperandType.NONE, 1),
    "H>F": Opcode(100, OperandType.NONE, 1),
    "H>G": Opcode(101, OperandType.NONE, 1),
    "A>GPIO": Opcode(102, OperandType.NONE, 1),
    "B>GPIO": Opcode(103, OperandType.NONE, 1),
    "GPIO>A": Opcode(104, OperandType.NONE, 1),
    "GPIO>B": Opcode(105, OperandType.NONE, 1),
    "X>A": Opcode(106, OperandType.NONE, 1),
    "X>B": Opcode(107, OperandType.NONE, 1),
    "Y>A": Opcode(108, OperandType.NONE, 1),
    "Y>B": Opcode(109, OperandType.NONE, 1),
    "PUSH_C": Opcode(110, OperandType.NONE, 1),
    "POP_C": Opcode(111, OperandType.NONE, 1),
    "PUSH_D": Opcode(112, OperandType.NONE, 1),
    "POP_D": Opcode(113, OperandType.NONE, 1),
    "PUSH_E": Opcode(114, OperandType.NONE, 1),
    "POP_E": Opcode(115, OperandType.NONE, 1),
    "PUSH_F": Opcode(116, OperandType.NONE, 1),
    "POP_F": Opcode(117, OperandType.NONE, 1),
    "PUSH_G": Opcode(118, OperandType.NONE, 1),
    "POP_G": Opcode(119, OperandType.NONE, 1),
    "PUSH_H": Opcode(120, OperandType.NONE, 1),
    "POP_H": Opcode(121, OperandType.NONE, 1),
    "B++": Opcode(122, OperandType.NONE, 1),
    "B--": Opcode(123, OperandType.NONE, 1),
    "JMP_COMP": Opcode(124, OperandType.NONE, 1),
    "GOSUB_COMP": Opcode(125, OperandType.NONE, 1),
    "CLEAR_INTER": Opcode(126, OperandType.NONE, 1),
    "HALT": Opcode(127, OperandType.NONE, 1),
    # Extended opcodes (128-254)
    "ADD_c": Opcode(128, OperandType.NONE, 1),
    "SUB_c": Opcode(129, OperandType.NONE, 1),
    "CMP_c": Opcode(130, OperandType.NONE, 1),
    "AB++": Opcode(131, OperandType.NONE, 1),
    "AB--": Opcode(132, OperandType.NONE, 1),
    "CD++": Opcode(133, OperandType.NONE, 1),
    "CD--": Opcode(134, OperandType.NONE, 1),
    "EF++": Opcode(135, OperandType.NONE, 1),
    "EF--": Opcode(136, OperandType.NONE, 1),
    "GH++": Opcode(137, OperandType.NONE, 1),
    "GH--": Opcode(138, OperandType.NONE, 1),
    "LOAD_A_EF": Opcode(139, OperandType.NONE, 1),
    "LOAD_B_EF": Opcode(140, OperandType.NONE, 1),
    "STORE_A_EF": Opcode(141, OperandType.NONE, 1),
    "STORE_B_EF": Opcode(142, OperandType.NONE, 1),
    "LOAD_A_GH": Opcode(143, OperandType.NONE, 1),
    "LOAD_B_GH": Opcode(144, OperandType.NONE, 1),
    "STORE_A_GH": Opcode(145, OperandType.NONE, 1),
    "STORE_B_GH": Opcode(146, OperandType.NONE, 1),
    "AB>>": Opcode(147, OperandType.NONE, 1),
    "AB<<": Opcode(148, OperandType.NONE, 1),
    "AB>OUT": Opcode(149, OperandType.NONE, 1),
    "AB+CD": Opcode(150, OperandType.NONE, 1),
    "AB-CD": Opcode(151, OperandType.NONE, 1),
    "CMP_16": Opcode(152, OperandType.NONE, 1),
    "LO_AB_CD": Opcode(153, OperandType.NONE, 1),
    "ST_AB_CD": Opcode(154, OperandType.NONE, 1),
    "LO_A_CD++": Opcode(155, OperandType.NONE, 1),
    "LO_B_CD++": Opcode(156, OperandType.NONE, 1),
    "ST_A_CD++": Opcode(157, OperandType.NONE, 1),
    "ST_B_CD++": Opcode(158, OperandType.NONE, 1),
    "LO_A_EF++": Opcode(159, OperandType.NONE, 1),
    "LO_B_EF++": Opcode(160, OperandType.NONE, 1),
    "ST_A_EF++": Opcode(161, OperandType.NONE, 1),
    "ST_B_EF++": Opcode(162, OperandType.NONE, 1),
    "LO_A_GH++": Opcode(163, OperandType.NONE, 1),
    "LO_B_GH++": Opcode(164, OperandType.NONE, 1),
    "ST_A_GH++": Opcode(165, OperandType.NONE, 1),
    "ST_B_GH++": Opcode(166, OperandType.NONE, 1),
    "SET_AB": Opcode(167, OperandType.IMM16, 3),
    "S_A>>": Opcode(168, OperandType.NONE, 1),
    "S_B>>": Opcode(169, OperandType.NONE, 1),
    "S_AB>>": Opcode(170, OperandType.NONE, 1),
    "CD>>": Opcode(171, OperandType.NONE, 1),
    "CD<<": Opcode(172, OperandType.NONE, 1),
    "EF>>": Opcode(173, OperandType.NONE, 1),
    "EF<<": Opcode(174, OperandType.NONE, 1),
    "GH>>": Opcode(175, OperandType.NONE, 1),
    "GH<<": Opcode(176, OperandType.NONE, 1),
    "AB>CD": Opcode(177, OperandType.NONE, 1),
    "AB>EF": Opcode(178, OperandType.NONE, 1),
    "AB>GH": Opcode(179, OperandType.NONE, 1),
    "CD>AB": Opcode(180, OperandType.NONE, 1),
    "CD>EF": Opcode(181, OperandType.NONE, 1),
    "CD>GH": Opcode(182, OperandType.NONE, 1),
    "EF>AB": Opcode(183, OperandType.NONE, 1),
    "EF>CD": Opcode(184, OperandType.NONE, 1),
    "EF>GH": Opcode(185, OperandType.NONE, 1),
    "GH>AB": Opcode(186, OperandType.NONE, 1),
    "GH>CD": Opcode(187, OperandType.NONE, 1),
    "GH>EF": Opcode(188, OperandType.NONE, 1),
    "A_ZERO": Opcode(189, OperandType.NONE, 1),
    "AB_ZERO": Opcode(190, OperandType.NONE, 1),
    "0>AB": Opcode(191, OperandType.NONE, 1),
    "1>AB": Opcode(192, OperandType.NONE, 1),
    "FFFF>AB": Opcode(193, OperandType.NONE, 1),
    "NAND": Opcode(194, OperandType.NONE, 1),
    "OR": Opcode(195, OperandType.NONE, 1),
    "NOR": Opcode(196, OperandType.NONE, 1),
    "XOR": Opcode(197, OperandType.NONE, 1),
    "NXOR": Opcode(198, OperandType.NONE, 1),
    "SET_CD": Opcode(199, OperandType.IMM16, 3),
    "SET_EF": Opcode(200, OperandType.IMM16, 3),
    "SET_GH": Opcode(201, OperandType.IMM16, 3),
    "TRG_HWI": Opcode(247, OperandType.NONE, 1),
    "AB>IV": Opcode(248, OperandType.NONE, 1),
    "IV>AB": Opcode(249, OperandType.NONE, 1),
    "SET_IV": Opcode(250, OperandType.IMM16, 3),
    "HWI>A": Opcode(251, OperandType.NONE, 1),
    "CLEAR_HWI": Opcode(252, OperandType.NONE, 1),
    "RETURN_HWI": Opcode(253, OperandType.NONE, 1),
    "HWI": Opcode(254, OperandType.NONE, 1),
}


def get_opcode(mnemonic: str) -> Opcode | None:
    """Look up an opcode by mnemonic (case-insensitive)."""
    return OPCODES.get(mnemonic.upper())
